html = open('./index.html','a')
html.write('<html>')
html.write('<head>')
html.write('<title>')
html.write('title')
html.write('</title>')
html.write("<link rel='stylesheet' href='./style.css'>")
html.write('</head>')
html.write('<body>')
html.write('</body>')
html.write('</html>')

html.close()
open('./style.css','x')
open('script.js','x')